apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometurbo
  namespace: turbo
  labels:
    app.kubernetes.io/name: prometurbo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: prometurbo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometurbo
    spec:
      # Update serviceAccount if needed
      serviceAccountName: prometurbo
      containers:
        - name: prometurbo
          # Replace the image tag with desired version
          image: icr.io/cpopen/turbonomic/prometurbo:<PROMETURBO_IMAGE_TAG>
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: prometurbo-config
              mountPath: /etc/prometurbo
              readOnly: true
        - name: turbodif
          # Replace the image tag with desired version
          image: icr.io/cpopen/turbonomic/turbodif:<TURBODIF_IMAGE_TAG>
          imagePullPolicy: IfNotPresent
          env:
            # Do not change the following environment variable
            - name: "TURBODIF_TARGET_TYPE_OVERWRITE"
              value: "Prometheus"
          args:
            - --v=2
          volumeMounts:
          - name: turbodif-config
            mountPath: /etc/turbodif
            readOnly: true
          - name: turbonomic-credentials-volume
            mountPath: /etc/turbonomic-credentials
            readOnly: true
          - name: varlog
            mountPath: /var/log
      volumes:
        - name: prometurbo-config
          configMap:
            name: prometurbo-config
        - name: turbodif-config
          configMap:
            name: turbodif-config
        - name: turbonomic-credentials-volume
          secret:
            defaultMode: 420
            optional: true
            secretName: turbonomic-credentials
        - name: varlog
          emptyDir: {}
      restartPolicy: Always
