apiVersion: v1
kind: Namespace
metadata:
  name: turbo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: turbo-user
  namespace: turbo
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1    
metadata:
  name: turbo-all-binding
subjects:
- kind: ServiceAccount
  name: turbo-user
  namespace: turbo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
