apiVersion: v1
kind: ServiceAccount
metadata:
  # Use this yaml to create a service account to run prometurbo.
  # Provide a value for name.
  # Update the namespace value if required.
  name: prometurbo
  namespace: turbo
