apiVersion: v1
kind: ConfigMap
metadata:
  name: turbodif-config
data:
  turbodif-config.json: |-
    {
      "communicationConfig": {
        "serverMeta": {
          "version": "<TURBONOMIC_SERVER_VERSION>",
          "turboServer": "https://<TURBO-SERVER-ADDRESS>:<PORT>"
        },
        "restAPIConfig": {
          "opsManagerUserName": "administrator",
          "opsManagerPassword": "<TURBO-SERVER-PASSWORD>"
        }
      },
      "targetConfig": {
        "targetName": "Prometheus",
        "targetAddress": "http://127.0.0.1:8081/metrics"
      },
      "targetTypeSuffix": ""
    }
