apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
{{- if eq .Values.roleName "prometurbo" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.roleName }}-{{ .Release.Name }}-{{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.turbonomic.io
    resources:
      - prometheusquerymappings
      - prometheusserverconfigs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
{{- end }}
---
kind: ClusterRoleBinding
# For OpenShift 3.4-3.7 use apiVersion: v1
# For kubernetes 1.9 use rbac.authorization.k8s.io/v1
# For kubernetes 1.8 use rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleBinding }}-{{ .Release.Name }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  # User creating this resource must have permissions to add this policy to the SA
  kind: ClusterRole
  # accepted values cluster-reader disc and monitoring.
  {{- if eq .Values.roleName "prometurbo" }}
  name: {{ .Values.roleName }}-{{ .Release.Name }}-{{ .Release.Namespace }}
  {{- else }}
  name: {{ .Values.roleName }}
  {{- end }}
  # For OpenShift v3.4 remove apiGroup line
  apiGroup: rbac.authorization.k8s.io

