apiVersion: charts.helm.k8s.io/v1alpha1
kind: Prometurbo
metadata:
  name: prometurbo-release
spec:
  # Default values copied from <project_dir>/helm-charts/prometurbo/values.yaml

  # Turbo server version and address
  serverMeta:
    version: 7.21
    turboServer: https://Turbo_server_URL

  # Turbo server api user and password stored in a secret or optionally specified as username and password
  # The opsManagerUserName requires Turbo administrator role
  #restAPIConfig:
    #turbonomicCredentialsSecretName: "turbonomic-credentials"
    #opsManagerUserName: Turbo_username
    #opsManagerPassword: Turbo_password
