apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometurbo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometurbo-operator
  template:
    metadata:
      labels:
        name: prometurbo-operator
    spec:
      serviceAccountName: prometurbo-operator
      containers:
        - name: prometurbo-operator
          # Replace this with the built image name
          image: turbonomic/prometurbo-operator:7.21
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "prometurbo-operator"
