apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometurbo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometurbo-operator
  template:
    metadata:
      labels:
        name: prometurbo-operator
    spec:
      serviceAccountName: prometurbo-operator
      securityContext:
        runAsNonRoot: true
      containers:
      - name: prometurbo-operator
        image: turbonomic/prometurbo-operator:8.6
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "prometurbo-operator"
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - mountPath: /tmp
          name: operator-tmpfs0
      volumes:
      - name: operator-tmpfs0
        emptyDir: {}
      terminationGracePeriodSeconds: 10
