kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometurbo-operator
subjects:
- kind: ServiceAccount
  name: prometurbo-operator
  namespace: turbo
roleRef:
  kind: Role
  name: prometurbo-operator
  apiGroup: rbac.authorization.k8s.io
