kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometurbo-operator
roleRef:
  kind: ClusterRole
  name: prometurbo-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: prometurbo-operator
    namespace: turbo
