# permissions for end users to view prometurboes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometurbo-viewer-role
rules:
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - prometurboes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - prometurboes/status
  verbs:
  - get
