# permissions for end users to edit prometurboes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometurbo-editor-role
rules:
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - prometurboes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - prometurboes/status
  verbs:
  - get
